[package]
name = "rust-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.19.7"
gtk4 = "0.8.2"
webkit2gtk = "2.0.1"
